import {
  Braces,
  GitCompareArrows,
  Hash,
  Database,
  Code,
  Search,
  FileCode,
  Clock,
  Fingerprint,
  Terminal,
  FileImage,
  Maximize2,
  Image,
  Crop,
  Pipette,
  RefreshCw,
  Sliders,
  EyeOff,
  Sun,
  Link2,
  Globe,
  Trash2,
  Tags,
  Bot,
  Map,
  Server,
  Calendar,
  Timer,
  Play,
  CalendarDays,
  CalendarRange,
  CalendarPlus,
  HelpCircle,
  FileSpreadsheet,
  LetterText,
  FileCode2,
  CaseSensitive,
  Volume2,
  ChevronsUpDown,
  AlignLeft,
  ListOrdered,
  Binary,
  KeyRound,
  Lock,
  Unlock,
  FileDown,
  Files,
  Scissors,
  FileText,
  FileMinus,
  FileUp,
  Settings,
  type LucideIcon,
} from "lucide-react";

export interface Tool {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  tagline: string;
  keywords: string[];
  icon: LucideIcon;
  href: string;
  isReady: boolean;
  category: "pdf" | "developer" | "office" | "image" | "web" | "time";
  targetSeoString: string;
}

export const tools: Tool[] = [
  // ── 1. PDF SUITE (16 Tools) ──
  {
    slug: "protect-pdf",
    name: "Protect PDF",
    targetSeoString: "Free Protect PDF Online | 100% Private | ToolsAtZero",
    shortName: "Protect PDF",
    description: "Encrypt and password-protect your PDF files 100% client-side.",
    tagline: "Encrypt and password-protect your PDF files",
    keywords: ["protect pdf", "password pdf", "encrypt pdf", "pdf security", "client-side"],
    icon: Lock,
    href: "/tools/protect-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    targetSeoString: "Free Unlock PDF Online | 100% Private | ToolsAtZero",
    shortName: "Unlock PDF",
    description: "Remove passwords and restriction blocks from PDF documents instantly.",
    tagline: "Remove password and restriction blocks from PDF",
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf unlocker", "client-side"],
    icon: Unlock,
    href: "/tools/unlock-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    targetSeoString: "Free Compress PDF Online | 100% Private | ToolsAtZero",
    shortName: "Compress PDF",
    description: "Reduce the file size of PDF documents while maintaining visual resolution.",
    tagline: "Reduce the size of your PDF files",
    keywords: ["compress pdf", "shrink pdf", "reduce pdf size", "pdf optimizer", "client-side"],
    icon: FileDown,
    href: "/tools/compress-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "crop-pdf",
    name: "Crop PDF",
    targetSeoString: "Free Crop PDF Online | 100% Private | ToolsAtZero",
    shortName: "Crop PDF",
    description: "Crop margins and adjust boundary coordinate boxes on PDF pages.",
    tagline: "Crop margins and adjust PDF layouts",
    keywords: ["crop pdf", "cut pdf pages", "pdf cropper", "adjust pdf boundaries", "client-side"],
    icon: Crop,
    href: "/tools/crop-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    targetSeoString: "Free Merge PDF Online | 100% Private | ToolsAtZero",
    shortName: "Merge PDF",
    description: "Combine multiple PDF documents into a single organized file.",
    tagline: "Combine multiple PDF files into one",
    keywords: ["merge pdf", "combine pdfs", "join pdf", "pdf merger", "client-side"],
    icon: Files,
    href: "/tools/merge-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    targetSeoString: "Free Split PDF Online | 100% Private | ToolsAtZero",
    shortName: "Split PDF",
    description: "Divide PDF documents into separate pages or custom range files.",
    tagline: "Extract pages and split PDF files",
    keywords: ["split pdf", "extract pdf pages", "separate pdf", "pdf splitter", "client-side"],
    icon: Scissors,
    href: "/tools/split-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "add-pdf-page-numbers",
    name: "Add Page Numbers",
    targetSeoString: "Free Add Page Numbers Online | 100% Private | ToolsAtZero",
    shortName: "Page Numbers",
    description: "Number PDF pages sequentially with custom positions and fonts.",
    tagline: "Add sequential page numbers to PDFs",
    keywords: ["pdf page numbers", "number pdf", "paginate pdf", "page numberer", "client-side"],
    icon: Hash,
    href: "/tools/add-pdf-page-numbers",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "add-watermark-to-pdf",
    name: "Add Watermark",
    targetSeoString: "Free Add Watermark Online | 100% Private | ToolsAtZero",
    shortName: "Watermark",
    description: "Add text stamp watermarks over your PDF sheets for copyright protection.",
    tagline: "Stamp custom text watermarks onto PDFs",
    keywords: ["watermark pdf", "pdf watermark", "stamp pdf", "copyright pdf", "client-side"],
    icon: FileText,
    href: "/tools/add-watermark-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "remove-pdf-pages",
    name: "Remove PDF Pages",
    targetSeoString: "Free Remove PDF Pages Online | 100% Private | ToolsAtZero",
    shortName: "Remove Pages",
    description: "Delete unnecessary pages from a PDF document locally.",
    tagline: "Delete select pages from a PDF document",
    keywords: ["remove pdf pages", "delete pdf pages", "clean pdf", "pdf page editor", "client-side"],
    icon: FileMinus,
    href: "/tools/remove-pdf-pages",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "pdf-extract-pages",
    name: "Extract Specific Pages",
    targetSeoString: "Free Extract Specific Pages Online | 100% Private | ToolsAtZero",
    shortName: "Extract Pages",
    description: "Isolate and save specific pages from your PDF file.",
    tagline: "Extract specific page indexes from a PDF",
    keywords: ["extract pdf pages", "pdf page extractor", "save pdf pages", "client-side"],
    icon: Files,
    href: "/tools/pdf-extract-pages",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "pdf-to-image",
    name: "PDF to Image",
    targetSeoString: "Free PDF to Image Online | 100% Private | ToolsAtZero",
    shortName: "PDF to Image",
    description: "Convert PDF sheets to PNG/JPG image files client-side.",
    tagline: "Render PDF document pages to images",
    keywords: ["pdf to image", "pdf to png", "pdf to jpg", "pdf render", "client-side"],
    icon: FileImage,
    href: "/tools/pdf-to-image",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    targetSeoString: "Free Image to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Image to PDF",
    description: "Compile PNG, JPG, and webp images into a clean PDF document.",
    tagline: "Compile multiple images into a PDF file",
    keywords: ["image to pdf", "convert images to pdf", "png to pdf", "jpg to pdf", "client-side"],
    icon: FileUp,
    href: "/tools/image-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    targetSeoString: "Free Excel to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Excel to PDF",
    description: "Format and export spreadsheet files (.xlsx/.csv) to PDF document layouts.",
    tagline: "Convert spreadsheets to PDF documents",
    keywords: ["excel to pdf", "xlsx to pdf", "csv to pdf", "spreadsheet export", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/excel-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    targetSeoString: "Free Word to PDF Online | 100% Private | ToolsAtZero",
    shortName: "Word to PDF",
    description: "Convert standard Word documents (.docx) to high-fidelity PDF pages.",
    tagline: "Convert Word documents to PDF layouts",
    keywords: ["word to pdf", "docx to pdf", "convert docx", "document conversion", "client-side"],
    icon: FileText,
    href: "/tools/word-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "powerpoint-to-pdf",
    name: "PowerPoint to PDF",
    targetSeoString: "Free PowerPoint to PDF Online | 100% Private | ToolsAtZero",
    shortName: "PPT to PDF",
    description: "Convert slide presentation formats (.pptx) to standard PDF pages.",
    tagline: "Convert slide presentations to PDF books",
    keywords: ["ppt to pdf", "powerpoint to pdf", "pptx to pdf", "slides converter", "client-side"],
    icon: FileText,
    href: "/tools/powerpoint-to-pdf",
    isReady: true,
    category: "pdf",
  },
  {
    slug: "edit-pdf-metadata",
    name: "Edit Metadata",
    targetSeoString: "Free Edit Metadata Online | 100% Private | ToolsAtZero",
    shortName: "PDF Metadata",
    description: "Edit PDF properties like author, title, keywords, and creation dates.",
    tagline: "Update properties and metadata of a PDF",
    keywords: ["edit pdf metadata", "pdf properties", "change pdf author", "pdf keywords", "client-side"],
    icon: Settings,
    href: "/tools/edit-pdf-metadata",
    isReady: true,
    category: "pdf",
  },

  // ── 2. DEVELOPER TOOLS (10 Tools) ──
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    targetSeoString: "Free JSON Formatter & Validator Online | 100% Private | ToolsAtZero",
    shortName: "JSON Formatter",
    description: "Beautify, validate, and minify JSON structures locally.",
    tagline: "Format, validate, and minify JSON data",
    keywords: ["json formatter", "validate json", "beautify json", "json validator", "client-side"],
    icon: Braces,
    href: "/tools/json-formatter",
    isReady: true,
    category: "developer",
  },
  {
    slug: "base64-encoder-decoder",
    name: "Base64 Encoder/Decoder",
    targetSeoString: "Free Base64 Encoder/Decoder Online | 100% Private | ToolsAtZero",
    shortName: "Base64",
    description: "Encode binary or text files into Base64 format and decode them back.",
    tagline: "Encode or decode Base64 data",
    keywords: ["base64 encoder", "base64 decoder", "encode text", "decode binary", "client-side"],
    icon: Binary,
    href: "/tools/base64-encoder-decoder",
    isReady: true,
    category: "developer",
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    targetSeoString: "Free JWT Decoder Online | 100% Private | ToolsAtZero",
    shortName: "JWT Decoder",
    description: "Inspect JSON Web Tokens (JWT) payload, headers, and signatures locally.",
    tagline: "Decode and inspect JWT auth tokens",
    keywords: ["jwt", "jwt decoder", "token decode", "json web token", "client-side"],
    icon: KeyRound,
    href: "/tools/jwt-decoder",
    isReady: true,
    category: "developer",
  },
  {
    slug: "text-diff-checker",
    name: "Text Diff Checker",
    targetSeoString: "Free Text Diff Checker Online | 100% Private | ToolsAtZero",
    shortName: "Diff Checker",
    description: "Compare text blocks side-by-side to highlight line-by-line differences.",
    tagline: "Compare text differences visually",
    keywords: ["text diff", "diff checker", "compare text", "difference checker", "client-side"],
    icon: GitCompareArrows,
    href: "/tools/text-diff-checker",
    isReady: true,
    category: "developer",
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    targetSeoString: "Free Hash Generator Online | 100% Private | ToolsAtZero",
    shortName: "Hash Gen",
    description: "Compute MD5, SHA-1, SHA-256, and SHA-512 hashes in your browser.",
    tagline: "Generate cryptographic checksum hashes",
    keywords: ["hash generator", "md5 generator", "sha256 hash", "checksum builder", "client-side"],
    icon: Hash,
    href: "/tools/hash-generator",
    isReady: true,
    category: "developer",
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    targetSeoString: "Free SQL Formatter Online | 100% Private | ToolsAtZero",
    shortName: "SQL Formatter",
    description: "Beautify and indent SQL queries with custom indentation levels.",
    tagline: "Beautify and indent SQL query scripts",
    keywords: ["sql formatter", "format sql", "beautify sql", "sql indent", "client-side"],
    icon: Database,
    href: "/tools/sql-formatter",
    isReady: true,
    category: "developer",
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON",
    targetSeoString: "Free XML to JSON Online | 100% Private | ToolsAtZero",
    shortName: "XML to JSON",
    description: "Convert XML data structures into clean JSON objects in memory.",
    tagline: "Convert XML documents to JSON structure",
    keywords: ["xml to json", "xml converter", "parse xml", "xml2json", "client-side"],
    icon: Code,
    href: "/tools/xml-to-json",
    isReady: true,
    category: "developer",
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    targetSeoString: "Free RegEx Tester Online | 100% Private | ToolsAtZero",
    shortName: "RegEx Tester",
    description: "Test regular expressions with syntax highlights and match breakdowns.",
    tagline: "Test regular expression match groups",
    keywords: ["regex tester", "regexp test", "javascript regex", "regex explainer", "client-side"],
    icon: Search,
    href: "/tools/regex-tester",
    isReady: true,
    category: "developer",
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    targetSeoString: "Free HTML Entity Encoder Online | 100% Private | ToolsAtZero",
    shortName: "HTML Entities",
    description: "Encode special characters to HTML entities and decode them back.",
    tagline: "Encode or decode HTML entities",
    keywords: ["html entities", "entity encoder", "html escape", "unescape html", "client-side"],
    icon: FileCode,
    href: "/tools/html-entities",
    isReady: true,
    category: "developer",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    targetSeoString: "Free UUID Generator Online | 100% Private | ToolsAtZero",
    shortName: "UUID Gen",
    description: "Bulk generate cryptographically secure UUID v4 tokens locally.",
    tagline: "Generate secure UUID/GUID v4 strings",
    keywords: ["uuid generator", "guid generator", "random uuid", "uuid v4", "client-side"],
    icon: Fingerprint,
    href: "/tools/uuid-generator",
    isReady: true,
    category: "developer",
  },

  // ── 3. OFFICE & TEXT TOOLS (8 Tools) ──
  {
    slug: "case-converter",
    name: "Advanced Case Converter",
    targetSeoString: "Free Advanced Case Converter Online | 100% Private | ToolsAtZero",
    shortName: "Case Converter",
    description: "Convert text camelCase, snake_case, UPPERCASE, and sentence structures.",
    tagline: "Change text cases and naming formats",
    keywords: ["case converter", "text converter", "snake case", "camelcase", "client-side"],
    icon: CaseSensitive,
    href: "/tools/case-converter",
    isReady: true,
    category: "office",
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    targetSeoString: "Free CSV to JSON Online | 100% Private | ToolsAtZero",
    shortName: "CSV to JSON",
    description: "Format table CSV spreadsheets into clean JSON array collections.",
    tagline: "Format spreadsheet CSV tables to JSON",
    keywords: ["csv to json", "convert csv", "parse csv", "table data", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/csv-to-json",
    isReady: true,
    category: "office",
  },
  {
    slug: "csv-to-excel",
    name: "CSV to Excel",
    targetSeoString: "Free CSV to Excel Online | 100% Private | ToolsAtZero",
    shortName: "CSV to Excel",
    description: "Convert comma-separated tables into Microsoft Excel spreadsheet (.xls) files.",
    tagline: "Convert CSV data to Excel spreadsheet tables",
    keywords: ["csv to excel", "csv to xls", "spreadsheet builder", "table converter", "client-side"],
    icon: FileSpreadsheet,
    href: "/tools/csv-to-excel",
    isReady: true,
    category: "office",
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    targetSeoString: "Free Word Counter Online | 100% Private | ToolsAtZero",
    shortName: "Word Counter",
    description: "Analyze word counts, reading speeds, sentence stats, and density scores.",
    tagline: "Analyze text statistics and density",
    keywords: ["word counter", "character counter", "text length", "word metrics", "client-side"],
    icon: LetterText,
    href: "/tools/word-counter",
    isReady: true,
    category: "office",
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    targetSeoString: "Free Find & Replace Online | 100% Private | ToolsAtZero",
    shortName: "Find & Replace",
    description: "Search text streams using string search or regex and replace matches.",
    tagline: "Search and replace text strings",
    keywords: ["find replace", "replace text", "find string", "regex replace", "client-side"],
    icon: ChevronsUpDown,
    href: "/tools/find-replace",
    isReady: true,
    category: "office",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    targetSeoString: "Free Lorem Ipsum Generator Online | 100% Private | ToolsAtZero",
    shortName: "Lorem Ipsum",
    description: "Generate mockup paragraphs, headings, and placeholder text loops.",
    tagline: "Generate layout placeholder dummy text",
    keywords: ["lorem ipsum", "dummy text", "placeholder generator", "layout text", "client-side"],
    icon: FileCode2,
    href: "/tools/lorem-ipsum",
    isReady: true,
    category: "office",
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    targetSeoString: "Free Remove Duplicate Lines Online | 100% Private | ToolsAtZero",
    shortName: "Remove Duplicates",
    description: "Filter duplicate lines out of list arrays in browser memory frames.",
    tagline: "Filter duplicate lines from lists",
    keywords: ["remove duplicate lines", "deduplicate list", "unique lines", "clean text", "client-side"],
    icon: AlignLeft,
    href: "/tools/remove-duplicate-lines",
    isReady: true,
    category: "office",
  },
  {
    slug: "sort-text-lines",
    name: "Sort Text Lines",
    targetSeoString: "Free Sort Text Lines Online | 100% Private | ToolsAtZero",
    shortName: "Sort Lines",
    description: "Sort lines alphabetically, numerically, reversely, or by length.",
    tagline: "Sort text lists and lines sequentially",
    keywords: ["sort lines", "sort text", "alphabetical sort", "reorder lines", "client-side"],
    icon: ListOrdered,
    href: "/tools/sort-text-lines",
    isReady: true,
    category: "office",
  },

  // ── 4. IMAGE TOOLS (8 Tools) ──
  {
    slug: "image-compressor",
    name: "Image Compressor",
    targetSeoString: "Free Image Compressor Online | 100% Private | ToolsAtZero",
    shortName: "Compress Image",
    description: "Compress JPEG, PNG, and WebP files client-side inside canvas frames.",
    tagline: "Compress images with zero quality loss",
    keywords: ["compress image", "shrink photo", "reduce size", "optimize jpg", "client-side"],
    icon: FileImage,
    href: "/tools/image-compressor",
    isReady: true,
    category: "image",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    targetSeoString: "Free Image Resizer Online | 100% Private | ToolsAtZero",
    shortName: "Resize Image",
    description: "Adjust image heights and widths using local canvas scaling parameters.",
    tagline: "Change canvas height and width dimensions",
    keywords: ["resize image", "scale photo", "change dimensions", "width scaler", "client-side"],
    icon: Maximize2,
    href: "/tools/image-resizer",
    isReady: true,
    category: "image",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    targetSeoString: "Free PNG to JPG Online | 100% Private | ToolsAtZero",
    shortName: "PNG to JPG",
    description: "Convert PNG images to JPEG format with custom quality sliders.",
    tagline: "Convert PNG files to JPG format",
    keywords: ["png to jpg", "convert png", "jpeg", "image format", "client-side"],
    icon: Image,
    href: "/tools/png-to-jpg",
    isReady: true,
    category: "image",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    targetSeoString: "Free JPG to PNG Online | 100% Private | ToolsAtZero",
    shortName: "JPG to PNG",
    description: "Convert JPEG files to PNG transparent image structures.",
    tagline: "Convert JPG files to PNG format",
    keywords: ["jpg to png", "jpeg to png", "convert jpg", "transparent png", "client-side"],
    icon: Image,
    href: "/tools/jpg-to-png",
    isReady: true,
    category: "image",
  },
  {
    slug: "image-cropper",
    name: "Image Cropper",
    targetSeoString: "Free Image Cropper Online | 100% Private | ToolsAtZero",
    shortName: "Crop Image",
    description: "Crop local photos and adjust boundary coordinate grids.",
    tagline: "Crop and adjust image coordinates",
    keywords: ["crop image", "cut photo", "cropping", "dimensions crop", "client-side"],
    icon: Crop,
    href: "/tools/image-cropper",
    isReady: true,
    category: "image",
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    targetSeoString: "Free Color Picker Online | 100% Private | ToolsAtZero",
    shortName: "Color Picker",
    description: "Extract color hex, rgb, and hsl codes from loaded image pixels.",
    tagline: "Extract colors from image pixel array",
    keywords: ["color picker", "hex color", "extract colors", "eyedropper", "client-side"],
    icon: Pipette,
    href: "/tools/color-picker",
    isReady: true,
    category: "image",
  },
  {
    slug: "base64-to-image",
    name: "Base64 to Image",
    targetSeoString: "Free Base64 to Image Online | 100% Private | ToolsAtZero",
    shortName: "Base64 to Image",
    description: "Render Base64 strings into visual images and download them.",
    tagline: "Render Base64 strings to images",
    keywords: ["base64 to image", "data uri", "decode base64", "base64 image", "client-side"],
    icon: RefreshCw,
    href: "/tools/base64-to-image",
    isReady: true,
    category: "image",
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG",
    targetSeoString: "Free SVG to PNG Online | 100% Private | ToolsAtZero",
    shortName: "SVG to PNG",
    description: "Rasterize vector SVG files into standard transparent PNG formats.",
    tagline: "Convert SVG vector strings to PNG format",
    keywords: ["svg to png", "vector to raster", "convert svg", "svg2png", "client-side"],
    icon: Sliders,
    href: "/tools/svg-to-png",
    isReady: true,
    category: "image",
  },

  // ── 5. WEB TOOLS (6 Tools) ──
  {
    slug: "url-encoder-decoder",
    name: "URL Encoder/Decoder",
    targetSeoString: "Free URL Encoder/Decoder Online | 100% Private | ToolsAtZero",
    shortName: "URL Encoder",
    description: "Encode or decode URL parameters with percent encoding.",
    tagline: "Encode or decode URL components",
    keywords: ["url encode", "url decode", "percent encoding", "uri encoder", "client-side"],
    icon: Link2,
    href: "/tools/url-encoder-decoder",
    isReady: true,
    category: "web",
  },
  {
    slug: "html-minifier",
    name: "HTML Minifier",
    targetSeoString: "Free HTML Minifier Online | 100% Private | ToolsAtZero",
    shortName: "HTML Minify",
    description: "Minify HTML pages by stripping whitespace characters and comments.",
    tagline: "Compress and minify HTML structures",
    keywords: ["html minifier", "minify html", "compress html", "page size minifier", "client-side"],
    icon: Trash2,
    href: "/tools/html-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    targetSeoString: "Free CSS Minifier Online | 100% Private | ToolsAtZero",
    shortName: "CSS Minify",
    description: "Compress CSS stylesheets by removing spacing rules and comments.",
    tagline: "Compress and minify CSS styles",
    keywords: ["css minifier", "minify css", "compress css", "clean stylesheets", "client-side"],
    icon: Trash2,
    href: "/tools/css-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "javascript-minifier",
    name: "JS Minifier",
    targetSeoString: "Free JS Minifier Online | 100% Private | ToolsAtZero",
    shortName: "JS Minifier",
    description: "Minify and compact JS script code structures locally.",
    tagline: "Compact and minify JS source code",
    keywords: ["js minifier", "minify javascript", "js compressor", "obfuscate js", "client-side"],
    icon: Trash2,
    href: "/tools/javascript-minifier",
    isReady: true,
    category: "web",
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    targetSeoString: "Free Meta Tag Generator Online | 100% Private | ToolsAtZero",
    shortName: "Meta Gen",
    description: "Generate SEO-optimized HTML header meta tag blocks.",
    tagline: "Generate HTML header SEO meta tags",
    keywords: ["meta tag generator", "seo meta", "og tags", "twitter cards", "client-side"],
    icon: Tags,
    href: "/tools/meta-tag-generator",
    isReady: true,
    category: "web",
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    targetSeoString: "Free Robots.txt Generator Online | 100% Private | ToolsAtZero",
    shortName: "Robots Gen",
    description: "Create search engine crawler instruction sitemaps.",
    tagline: "Generate custom Robots.txt rules text",
    keywords: ["robots txt", "robots.txt generator", "crawler rules", "sitemap index", "client-side"],
    icon: Bot,
    href: "/tools/robots-txt-generator",
    isReady: true,
    category: "web",
  },

  // ── 6. TIME TOOLS (4 Tools) ──
  {
    slug: "epoch-converter",
    name: "Epoch Converter",
    targetSeoString: "Free Epoch Converter Online | 100% Private | ToolsAtZero",
    shortName: "Epoch",
    description: "Convert Unix timestamps to local and UTC date formatting.",
    tagline: "Convert Unix epoch timestamps to dates",
    keywords: ["epoch converter", "unix timestamp", "epoch time", "milliseconds convert", "client-side"],
    icon: Calendar,
    href: "/tools/epoch-converter",
    isReady: true,
    category: "time",
  },
  {
    slug: "time-zone-converter",
    name: "Time Zone Converter",
    targetSeoString: "Free Time Zone Converter Online | 100% Private | ToolsAtZero",
    shortName: "Timezones",
    description: "Convert date times across multiple regional global zones.",
    tagline: "Compare and convert global timezones",
    keywords: ["timezone converter", "convert time zone", "gmt utc est", "teams timezone", "client-side"],
    icon: Globe,
    href: "/tools/time-zone-converter",
    isReady: true,
    category: "time",
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    targetSeoString: "Free Date Difference Calculator Online | 100% Private | ToolsAtZero",
    shortName: "Date Difference",
    description: "Compute the number of years, months, and days between target dates.",
    tagline: "Calculate days elapsed between date inputs",
    keywords: ["date difference", "days between dates", "date calculator", "years difference", "client-side"],
    icon: CalendarDays,
    href: "/tools/date-difference",
    isReady: true,
    category: "time",
  },
  {
    slug: "time-calculator",
    name: "Add/Subtract Time",
    targetSeoString: "Free Add/Subtract Time Online | 100% Private | ToolsAtZero",
    shortName: "Time Calc",
    description: "Add or subtract duration offsets from a starting date.",
    tagline: "Perform duration arithmetic on dates",
    keywords: ["add time to date", "time calculator", "subtract time", "date offsets", "client-side"],
    icon: CalendarPlus,
    href: "/tools/time-calculator",
    isReady: true,
    category: "time",
  },
];

export const readyTools = tools.filter((t) => t.isReady);
export const comingSoonTools = tools.filter((t) => !t.isReady);
